// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCciTBEz7ayUB2-di7yJvXxzmjA62lsU',
    appId: '1:501433622237:web:9adccb7cbfdfe16ad00534',
    messagingSenderId: '501433622237',
    projectId: 'skillswapprojet',
    authDomain: 'skillswapprojet.firebaseapp.com',
    storageBucket: 'skillswapprojet.firebasestorage.app',
    measurementId: 'G-HJXSLRLS8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQmzlsTddsvvlx-24eb2HZZvsTfA5q70',
    appId: '1:501433622237:android:6a9f77e1b788988bd00534',
    messagingSenderId: '501433622237',
    projectId: 'skillswapprojet',
    storageBucket: 'skillswapprojet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMEWiDrkJJwAvWQ2ohVnc3-EF37ZvVBc',
    appId: '1:501433622237:ios:b9596a714241faf0d00534',
    messagingSenderId: '501433622237',
    projectId: 'skillswapprojet',
    storageBucket: 'skillswapprojet.firebasestorage.app',
    iosBundleId: 'com.example.skillswapprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMEWiDrkJJwAvWQ2ohVnc3-EF37ZvVBc',
    appId: '1:501433622237:ios:b9596a714241faf0d00534',
    messagingSenderId: '501433622237',
    projectId: 'skillswapprojet',
    storageBucket: 'skillswapprojet.firebasestorage.app',
    iosBundleId: 'com.example.skillswapprojet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCciTBEz7ayUB2-di7yJvXxzmjA62lsU',
    appId: '1:501433622237:web:a856318793556142d00534',
    messagingSenderId: '501433622237',
    projectId: 'skillswapprojet',
    authDomain: 'skillswapprojet.firebaseapp.com',
    storageBucket: 'skillswapprojet.firebasestorage.app',
    measurementId: 'G-J4RES9QMP5',
  );
}
